#!/bin/sh

echo "======================================"
echo "     PRE-COMMIT SECURITY CHECK"
echo "======================================"

gitleaks protect --staged --config .gitleaks.toml --redact
RESULT=$?

if [ $RESULT -ne 0 ]; then
    echo ""
    echo "COMMIT BLOCKED"
    echo "Security issue detected."
    exit 1
fi

echo ""
echo "Security check passed."
exit 0