FROM node:22

WORKDIR /juice-shop

COPY package*.json ./

RUN npm install --ignore-scripts

RUN npm rebuild sqlite3

COPY . .

RUN cd frontend && npm install --legacy-peer-deps

RUN cd frontend && npx ng build --configuration production

RUN npm run build:server

EXPOSE 3000

CMD ["node", "build/app.js"]