name: DevSecOps Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  # ------- Etape 1 : build de base (backend uniquement) -------
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install backend dependencies only
        run: npm install --ignore-scripts --fetch-retries=5 --fetch-retry-mintimeout=20000 --fetch-retry-maxtimeout=120000

      - name: Build backend
        run: npm run build:server
  # ------- SAST : analyse du code source -------
  sast:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v4

      - name: Semgrep report
        run: semgrep scan --config=p/owasp-top-ten --json --output=semgrep-report.json
        continue-on-error: true

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json

      - name: Semgrep security gate
        run: semgrep scan --config=p/owasp-top-ten --error